In [1]:
import pandas as pd

In [2]:
ps=pd.read_csv('primarysector.csv')

In [3]:
ps.head()

,Year,Claim Year Quarter,Program ID,Program Name,Primary Sector,Building Type,Climate Zone,Claim Total Expenditures
0,2016,2016YR,BAYREN01,Single Family,Residential,Residential Single Family,12,3797947.34
1,2016,2016YR,BAYREN01,Single Family,Residential,Residential Single Family,2,1515396.32
2,2016,2016YR,BAYREN01,Single Family,Residential,Residential Single Family,3A,912459.69
3,2016,2016YR,BAYREN01,Single Family,Residential,Residential Single Family,3B,566865.90
4,2016,2016YR,BAYREN01,Single Family,Residential,Residential Single Family,4,1275836.75

In [4]:
public_sector=ps[ps['Primary Sector']=='Public']

In [5]:
public_sector.head()

,Year,Claim Year Quarter,Program ID,Program Name,Primary Sector,Building Type,Climate Zone,Claim Total Expenditures
1069,2016,2016YR,PGE2110011,California Community Colleges,Public,Assembly,4,1270572.50
1070,2016,2016YR,PGE2110011,California Community Colleges,Public,Commercial,11,6041.31
1071,2016,2016YR,PGE2110011,California Community Colleges,Public,Commercial,12,135871.53
1072,2016,2016YR,PGE2110011,California Community Colleges,Public,Commercial,2,279086.05
1073,2016,2016YR,PGE2110011,California Community Colleges,Public,Commercial,3A,39372.43

In [6]:
public_sector.shape

(2773, 8)

In [7]:
ps.shape

(14115, 8)

In [8]:
san_mateo_county = pd.read_csv('Claimed_Energy_Efficiency_by_City.csv')

In [9]:
san_mateo_county.rename(columns = {'City': 'Program ID'})

,Program ID,Claimed Year,Program,Gross kW,Gross kWh,Gross Therms,Incentives,Location 1
0,Belmont,01/01/2015 12:00:00 AM,Residential,0.00,0.0,0.0,10750.0,"Belmont\n(37.508536, -122.291951)"
1,Half Moon Bay,01/01/2013 12:00:00 AM,Government Partnerships,6.43,29056.0,0.0,6223.0,"Half Moon Bay\n(37.463638, -122.429242)"
2,San Mateo,01/01/2015 12:00:00 AM,Commercial,8.42,108004.0,-197.0,5734.0,"San Mateo\n(37.547166, -122.314351)"
3,Burlingame,01/01/2016 12:00:00 AM,Commercial,2.90,2545.0,0.0,4637.0,"Burlingame\n(37.584195, -122.366265)"
4,San Bruno,01/01/2015 12:00:00 AM,Commercial,0.00,0.0,1807.0,353.0,"San Bruno\n(37.627277, -122.416148)"
...,...,...,...,...,...,...,...,...
993,San Bruno,01/01/2017 12:00:00 AM,Commercial,49.99,225079.0,8706.0,65814.0,"San Bruno\n(37.627277, -122.416148)"
994,Redwood City,01/01/2014 12:00:00 AM,Commercial,0.24,156.0,0.0,100.0,"Redwood City\n(37.484778, -122.22815)"
995,San Mateo,01/01/2014 12:00:00 AM,Commercial,-0.06,-2608.0,6667.0,12250.0,"San Mateo\n(37.547166, -122.314351)"
996,Atherton,01/01/2015 12:00:00 AM,Residential,7.30,48553.0,502.0,12000.0,"Atherton\n(37.461318, -122.19843)"
997,Moss Beach,01/01/2014 12:00:00 AM,Residential,1.20,6946.0,89.0,1905.0,"Moss Beach\n(37.527471, -122.513396)"

In [19]:
public_sector.merge(san_mateo_county)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [10]:
san_mateo_county_municipal = pd.read_csv('Municipal_Operations_Energy_Efficiency.csv')

In [11]:
san_mateo_county_municipal.head()

,Jurisdiction,Reported Year,Technology Family,Technology,Annual Incentives,Annual Electricity Demand Savings (kW),Annual Electricity Consumption Savings (kWh),Annual Gas Savings (therms),Energy Savings (MBTU),Electricity Emissions Avoided (MT CO2),Natural Gas Emissions Avoided (MT CO2),Total Emissions Avoided (MT CO2)
0,Atherton,01/01/2012 12:00:00 AM,LIGHTING,LINEAR FLUORESCENT,5234.14,9.0,36777.0,0.0,125,7.42,0.0,7.42
1,Atherton,01/01/2012 12:00:00 AM,LIGHTING,LINEAR FLUORESCENT,4708.68,7.9,32462.0,0.0,111,6.55,0.0,6.55
2,Atherton,01/01/2012 12:00:00 AM,LIGHTING,LINEAR FLUORESCENT,2071.81,3.5,14194.0,0.0,48,2.87,0.0,2.87
3,Atherton,01/01/2012 12:00:00 AM,LIGHTING,COMPACT FLUORESCENT,720.56,2.0,7962.0,0.0,27,1.61,0.0,1.61
4,Atherton,01/01/2012 12:00:00 AM,LIGHTING,COMPACT FLUORESCENT,556.05,0.0,6572.0,0.0,22,1.33,0.0,1.33

In [12]:
partnership = pd.read_csv('Partnership Data as of 2021-01-13.csv')

In [13]:
partnership.columns

Index(['project_key', 'project_id', 'project_name', 'project_created_date',
       'accrual_milestone_date', 'project_status', 'project_system',
       'project_campus', 'project_type', 'electric_or_gas_only',
       ...
       'verified_savings_kwh', 'verified_savings_therm',
       'verified_savings_kw_real', 'verified_savings_kwh_real',
       'verified_savings_therm_real', 'verified_savings_ghg', 'na.rm',
       'note_recent_date', 'note_recent_taker', 'note_recent'],
      dtype='object', length=102)

In [14]:
partnership.head()

,project_key,project_id,project_name,project_created_date,accrual_milestone_date,project_status,project_system,project_campus,project_type,electric_or_gas_only,...,verified_savings_kwh,verified_savings_therm,verified_savings_kw_real,verified_savings_kwh_real,verified_savings_therm_real,verified_savings_ghg,na.rm,note_recent_date,note_recent_taker,note_recent
0,0064516a,CSUNR-91881B,Nordhoff Hall (CLIP),2020-11-23,2021-04-23,ACTIVE,CSU,CSU Northridge,RETROFIT,Electric Only,...,0.0,0.0,0.0,0.0,0.0,0.0,True,2020-12-23 09:36:32,christine@arc-alternatives.com,NTP issued 11/25. Project In Progress.
1,007aaaab,D-07220S,Rolfe Hall Corridor Lighting,2020-10-13,2021-07-29,ACTIVE,UC,UC Los Angeles,RETROFIT,Electric Only,...,0.0,0.0,0.0,0.0,0.0,0.0,True,2020-11-16 14:53:05,christine@arc-alternatives.com,extension granted to 6/29/2021 - RL
2,012260b0,CSUNR-76636H,Magnolia (CLIP),2020-12-23,2021-12-23,ACTIVE,CSU,CSU Northridge,RETROFIT,Electric Only,...,0.0,0.0,0.0,0.0,0.0,0.0,True,2020-12-23 14:27:55,christine@arc-alternatives.com,12/23 - Project entered into database from CSU...
3,057ecb74,CSUNR-18740A,Info Booths (CLIP),2020-12-28,2021-04-28,ACTIVE,CSU,CSU Northridge,RETROFIT,Electric Only,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2020-12-28 12:23:47,christine@arc-alternatives.com,12/28 - Project entered into database from CSU...
4,09e870cd,CSUNR-26326F,Eucalyptus (CLIP),2020-12-28,2021-04-28,ACTIVE,CSU,CSU Northridge,RETROFIT,Electric Only,...,0.0,0.0,0.0,0.0,0.0,0.0,True,2020-12-28 11:53:36,christine@arc-alternatives.com,12/28 - Project entered into database from CSU...

In [15]:
relevent = []

for e in partnership.columns:
    if 'cost' in e:
        relevent.append(e)

In [16]:
print(relevent)
relevent.append('project_campus')

['project_appl_cost', 'project_appl_ele_cost_cap', 'project_appl_gas_cost_cap', 'project_appr_cost', 'project_appr_ele_cost_cap', 'project_appr_gas_cost_cap', 'project_ver_cost', 'project_ver_ele_cost_cap', 'project_ver_gas_cost_cap', 'best_cost', 'best_ele_cost_cap', 'best_gas_cost_cap']

In [17]:
partnership['project_']

KeyError: 'project_'

In [ ]:
memory_saved = []
for i in df.columns:
	if df[i].dtype == 'str' or 'object':
    	mem = df.memory_usage().loc[i]
        
        df[i] = df[i].astype('categoruical)
        mem2 = df.memory_usage().loc[i]
                             
        memory_saved.append(mem2-mem)

could also make function for entire df

In [ ]:
pd.merge(
  			left= df, right= df2, 
  			left_on= 'Id1', right_on='name',
  			how='left'
) 

df.merge(df2, left_on='Name', right_on='name', how='left')

df.merge(df2, on='name')

how='1:m' 
how='m:m'
how='m:1'

In [ ]:
pd.merge(
  			left= df, right= df2, 
  			left_on= ['First Name', 'Last Name'], right_on=['first','last'],
  			how='left'
) 

pd.merge(
  			left= df, right= df2, 
  			on= ['First Name', 'Last Name'],
  			how='left'
)